name: darttel
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  teledart: any
  hive: any
  # path: ^1.8.0

dev_dependencies:
  build_runner: any
  hive_generator: any
  lints: ^2.0.0
  test: ^1.21.0
